apiVersion: apps/v1
kind: Deployment
metadata:
  name: railsaarthi-ml
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml
  template:
    metadata:
      labels:
        app: ml
    spec:
      containers:
        - name: ml
          image: railsaarthi-ml:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000